name: Deploy to Heroku Server

on:
  push:
    branches:
      - main

jobs:
  code-quality-check-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm run prettier:write
          npm run husky
